### ISSUE TITLE
Custom Video Capturer example does not run as is.

### ISSUE THREAD

**Issue by MichaelCG8** [opentok/opentok-macos-sdk-samples#16]
**Describe the bug**
Unlike all the other examples in this repo, I can't run the custom video capturer as is.
It crashes with EXC_BAD_ACCESS on line 59 of OTVideoCaptureProxy.m. The line of code is `    OTMacDefaultVideoCapturer* proxy = (__bridge OTMacDefaultVideoCapturer *)(capturer_cb->user_data);
`

**To Reproduce**
Clone the repo, install the sdk using SPM, set the signing team to your team. Build and run.

**Expected behavior**
No crash, I presume it's meant to behave much like the Basic capture example, but with modifiable behaviour.

**Screenshots**
N/A

**Device (please compete the following information):**
- sessionId, if applicable:
- macOS SDK version: VonageClientSDKVideoMacOS 2.25.3
- OS and version: 12.6.8, M1 CPU.

**Additional context**

**Comment by rktalusani** [comment]
created a PR with fix PR #17

**Comment by v-kpheng** [comment]
@MichaelCG8, the issue should be fixed, given https://github.com/opentok/opentok-macos-sdk-samples/pull/17 was merged in.  

Any issues, please let us know.  Thanks!
