### ISSUE TITLE
When using custom audio driver, system output volume is very low.

### ISSUE THREAD

**Issue by rktalusani** [opentok/opentok-macos-sdk-samples#9]
**Describe the bug**
When running the custom audio driver sample, as soon as you connect to the session the system output volume become very low. So if there was a audio player running, as soon as you connect to the session you would notice that you can hardly hear the music from the player.

**To Reproduce**
1. start playing music using music player
2. connect to the session.
3. music player volume become very low.

**Expected behavior**
There should not be any change in volume level.

**Screenshots**

**Device (please compete the following information):**
- macOS SDK version: 2.24.0
- OS and version: Monterey 12.6.3

**Additional context**
We are using audio unit with subType kAudioUnitSubType_VoiceProcessingIO.

**Comment by YoavGro** [comment]
HI,

Jumping on this.
We also tried implementing the Audio renderer, and we discovered the same issue.
One thing to note, is that this is also happening without being connected to the OpenTok session.
I think this has to do with how the kAudioUnitSubType_VoiceProcessingIO AudioUnit is working on the MacOS.
Might be good to check the render callback and see what can be done there.

**Comment by v-kpheng** [comment]
Thanks for letting us know about this issue.  We've added this to our backlog: https://jira.vonage.com/browse/VIDCS-635.

**Comment by YoavGro** [comment]
@v-kpheng can't seems to log in to your JIRA
Any update on this?
Is this expected to be fixed on V1?

**Comment by v-kpheng** [comment]
@YoavGro, only employees can access the link.  There's no ETA for when this will be fixed, but it has been added to our backlog.

Lastly, this is unlikely to be fixed in the next release.

**Comment by beHaze** [comment]
Fixed in 2.25.2
